name: Build and run tests

'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run lint 
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run test
        run: npm run test
